export const WS_ALL_CONNECTION_START = 'WS_ALL_CONNECTION_START';
export const WS_OWNER_CONNECTION_START = 'WS_OWNER_CONNECTION_START';

export const WS_ALL_CLOSE = 'WS_ALL_CLOSE';
export const WS_OWNER_CLOSE = 'WS_OWNER_CLOSE';