export type TWS_ALL_CONNECTION_START = 'WS_ALL_CONNECTION_START';
export type TWS_OWNER_CONNECTION_START = 'WS_OWNER_CONNECTION_START';
export type TWS_ALL_CLOSE = 'WS_ALL_CLOSE';
export type TWS_OWNER_CLOSE = 'WS_OWNER_CLOSE';

export type TActions = TWS_ALL_CONNECTION_START | TWS_OWNER_CONNECTION_START | TWS_ALL_CLOSE | TWS_OWNER_CLOSE;